### ISSUE TITLE
Drainer's memory usage exponentially increases when filtering too many DELETE events, leading to OOM

### ISSUE THREAD

**Issue by kennytm** [pingcap/tidb-binlog#1317]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

    1. On upstream, DELETE 1000 rows and INSERT 1 row per transaction, for many transactions
    2. On drainer, use the `binlog-filter-rule` to filter out all DELETE events, leaving only the INSERT.

3. What did you expect to see?

    * Synchronize normally.

4. What did you see instead?

    * The memory usage of drainer grows exponentially and eventually triggered kernel OOM.

5. Please provide the relate downstream type and version of drainer.
(run `drainer -V` in terminal to get drainer's version)

    * Both Drainer v5.4.1 and Drainer v6.5.3.

**Comment by kennytm** [comment]
Config:

```toml
[syncer.binlog-filter-rule]
[syncer.binlog-filter-rule.rule1]
ignore-event = ["delete"]

[[syncer.table-migrate-rule]]
binlog-filter-rule = ["rule1"]
source = { schema = "db", table = "tbl1" }

[[syncer.table-migrate-rule]]
binlog-filter-rule = ["rule1"]
source = { schema = "db", table = "tbl2" }

...
```
